# Generated by Django 2.2.4 on 2019-09-14 08:07

from django.db import migrations


def fulfill_new_building_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)


class Migration(migrations.Migration):
    dependencies = [('property', '0003_flat_new_building')]

    operations = [migrations.RunPython(fulfill_new_building_field)]
