# Generated by Django 2.2.4 on 2019-09-14 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0005_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='likes',
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'
            ),
        )
    ]
