# Generated by Django 2.2.4 on 2019-09-14 09:37

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [('property', '0008_auto_20190914_1154')]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owner_phone_pure',
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                region=None,
                verbose_name='Нормализованный номер владельца',
            ),
        )
    ]
