# Generated by Django 2.2.4 on 2019-09-14 10:10

from django.db import migrations


def link_flats_to_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all():
        owner = Owner.objects.filter(
            owner_initials=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_phone_pure=flat.owner_phone_pure,
        ).first()
        if owner:
            owner.owner_flats.add(flat)


class Migration(migrations.Migration):
    dependencies = [('property', '0011_auto_20190914_1254')]

    operations = [migrations.RunPython(link_flats_to_owners)]
